# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 58250d92a5b55fa981781ecb491fb58cbd993eb38dd85b42cd7804a61e536472a9c5548f0b23ae28304f9db7cdb271e4c6a8cf374eb54bcb0b1be2be86574457

test:
  secret_key_base: 4b0727c28be03bc47a660a7edeec0540ceabd8653b5323c9fc37cd1aa4c49e18209c2d274e28addf42ef4e746f5b2ee8c5bbb5cbe0d922c52f403ff8f456fe5d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
